/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Seat.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

type Vec = {
  position: number[],
  rotation: numebr[]
}

export function Seat({position, rotation}: Vec, props) {
  const { nodes, materials } = useGLTF('/Seat-transformed.glb')
  return (
    <group {...props} dispose={null} position={position} rotation={rotation} scale={0.1}>
      <mesh geometry={nodes.Bench_2.geometry} material={materials.Wood} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/Seat-transformed.glb')
