/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 terrain1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useScroll } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"

import { lerp } from "three/src/math/MathUtils"

export function Model(props) {
  const { nodes, materials } = useGLTF('/terrain1-transformed.glb')
  const centerRef = useRef<THREE.Group | undefined>()
  const scroll = useScroll()

  useFrame((state) => {
      if (centerRef.current) {
          centerRef.current.rotation.y = lerp(0, 6.28, scroll.offset)
      }
  })

  return (
    <group {...props} dispose={null} position={[0, -3.8, 2.5]} rotation={[(Math.PI / 180) * 60, 2, 0]} ref={centerRef}>
      <mesh geometry={nodes.Circle.geometry} material={materials['base.001']} />
    </group>
  )
}

useGLTF.preload('/terrain1-transformed.glb')
