/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 trees.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tree(props) {
  const { nodes, materials } = useGLTF('/trees-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, -3, 3]} rotation={[(Math.PI / 180) * 60, 0, 0]} scale={0.015}>
      <mesh geometry={nodes.DeadTree_10.geometry} material={materials.MapleTree_Bark} position={[15.32, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.DeadTree_9.geometry} material={materials.MapleTree_Bark} position={[19.14, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.DeadTree_8.geometry} material={materials.MapleTree_Bark} position={[25.1, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.DeadTree_7.geometry} material={materials.MapleTree_Bark} position={[34.03, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.DeadTree_6.geometry} material={materials.MapleTree_Bark} position={[38.29, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/trees-transformed.glb')
