/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fire.glb -t -- --transform
Author: Afloat Above the World (https://sketchfab.com/ilikecatsnotdogs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-campfire-a1637e2556b44876b3d98bf203d4e9c4
Title: Low Poly Campfire
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { EffectComposer, Bloom, ToneMapping } from '@react-three/postprocessing'

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    Fire: THREE.MeshStandardMaterial
    Fire1: THREE.MeshPhysicalMaterial
    stone: THREE.MeshStandardMaterial
    wood: THREE.MeshStandardMaterial
  }
}

type ActionName = 'FireAction.001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Fire(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials, animations } = useGLTF('/fire.glb') as GLTFResult
  // const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group {...props} dispose={null} scale={1.2}>
            <EffectComposer disableNormalPass>
        <Bloom mipmapBlur luminanceThreshold={1}/>
      </EffectComposer>
      <group name="Sketchfab_Scene" position={[-38,.2, -6.1]}>
        <group name="Sketchfab_model" position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Fire_2" scale={[1.01, 1, 1]} >
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Fire} material-toneMapping={false} material-emissiveIntensity={1}/>
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Fire1} material-toneMapping={false} material-emissiveIntensity={40}/>
              </group>
              <group name="Stones_0">
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.stone} />
              </group>
              <group name="logs_1">
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.wood} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fire.glb')
