/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 treeb.glb -t -- --transform
Author: roguenoodle (https://sketchfab.com/roguenoodle)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-fantasy-tree-e-0b462614f3dc49029494ea84f582d236
Title: Medieval Fantasy -Tree E
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Instances, Instance } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mff_tree_pine_2_0: THREE.Mesh
  }
  materials: {
    medievalfantasyforest_unwrap: THREE.MeshStandardMaterial
  }
}

export function Treeb(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/treeb.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[-43, 0, -7]} >
        <Instances limit={10} range={100} geometry={nodes.mff_tree_pine_2_0.geometry} material={materials.medievalfantasyforest_unwrap} >
          {/* <Instance position={[3, -2, .4]} rotation={[0, 0, .8]} scale={1.21}/>
          <Instance position={[-1, -2, -.11]} rotation={[0, 0, .8]} scale={1.21}/>
          <Instance position={[3.4, 2, .7]} rotation={[0, 0, .2]} scale={.92}/> */}

          {/* old */}
          <Instance/>
          <Instance position={[-2, -4, 0]}/>
          <Instance position={[1.7, -2, -.11]} rotation={[0, 0, .8]} scale={1.21}/>
          <Instance position={[-4.5, -1, 0]} rotation={[0, 0, .8]}/>
        </Instances>
      </group>
    </group>
  )
}

useGLTF.preload('/treeb.glb')
